### ISSUE TITLE
Real world example

### ISSUE THREAD

**Issue by mhart** [mcavage/node-leader#1]
This project looks awesome! I've been waiting / wanting to do something like this myself for quite a while in Node, but haven't had enough real experience with ZK to do it.

I'd love to see a real world example when the lib is up to it - say, a simple example to manage master promotion in Redis or something like that. Would that be doable?

**Comment by mcavage** [comment]
Yeah definitely. That's the next phase of my project anyway so after
I've battle tested it I'll put up a tutorial or something. Stay tuned
for a bit (couple of weeks?).

Sent from my iPhone

On Jan 24, 2012, at 10:08 PM, Michael Hart
reply@reply.github.com
wrote:

**Comment by mhart** [comment]
Any progress on this? :-)

**Comment by mcavage** [comment]
Well, kind of :)

We're working through a Postgres master-promotion scheme at my day job with this now.  I didn't forget about this issue ;)

**Comment by DTrejo** [comment]
+1 :)

(especially for the redis example hehe)

Cheers,
D

**Comment by mhart** [comment]
Closing – I assume this is dead
